title: Markiian Strohyi
description: >
  MSc in Quantitative Finance | Aspiring Quantitative Analyst | Risk Modeling & Data Science | Python, SQL, Excel
theme: jekyll-theme-minimal
show_downloads: false
author: Markiian Strohyi
email: markiian.strohyi@gmail.com
social:
  links:
    - https://github.com/markiianstrohyi
    - https://www.linkedin.com/in/markiianstrohyi
plugins:
  - jekyll-seo-tag