title: Markiian Strohyi
description: >
  MSc Student in Quantitative Finance at University of Warsaw | 
  BSc in Finance, International Investment & Accounting | 
  Aspiring Quantitative Analyst | Risk Modeling & Data Science 
theme: jekyll-theme-minimal
show_downloads: false
author: Markiian Strohyi
email: markiianstrohyi@gmail.com
social:
  links:
    - https://github.com/markiianstrohyi
    - https://www.linkedin.com/in/markiian-strohyi-a50186252/
plugins:
  - jekyll-seo-tag